sudo: required
language: java
dist: trusty
matrix:
  include:
  - env:
    - TESTS=true
    - COVERAGE=true
  - env:
    - CROSSDOCK=true
services:
- docker
env:
  global:
  - DOCKER_VERSION=1.11.1-0~trusty
  - DOCKER_COMPOSE_VERSION=1.7.0
  - COMMIT=${TRAVIS_COMMIT::8}
  # SONATYPE_USERNAME
  - secure: JtVziSLqhV/3YliVa2ydZzMJ4mmtpA1NzDhQvvxVuvlxDRQyn6MX99gQ5BDePrL9Xu8zY5U0+hjhCHBxG1Jx3cQMKCujp+jfBpBiX7ld3JLhq4mSl0+cCYsCyDqNGfZ3OFzFCOhiWh9+gxICuAgbGwp3rlnpAWkEflaicYLVL7QKhZ7kYp7PcA3wMoT51F+RG4l/aNoA4Dz7E3xGrROIBAIn+1oUJKx5NeLH2B3rMNyKhcOnISx1X3w6eztVhZW6/OrsSN3QWlNN4lwQQzf1dgQ1Of0hoxPVxuM5SpBm05xPBqs5jDf3PMvEC380ZPJEwK1dm/aVYSQlcDRQb9iLAI2n2ayZHX2vBUpZcKaMjh5bxdboOTypbUzQq9KI46JyhRSDC8OWgKOpJG9st/OfQSQpQfleHniGtaUHeTuhBx1kwOIIRrDjSuiylJMSLdBfpPG4dRF1PfpnMswQiQDaznG1UoLuvgPn7s6efc35r4fi+FSr5pSRmGU3LFcJa5F4WnInULhkHD5/VCUExbn/09C6ob9JOVWt5oR8yGa4gImhpyG64qb/oE2RZH+0kkppiKdm3ZXL3NdYuH8leh+WT6kPrqpLvgFzvX5Zxzs+v8XvR9qDFlfCEUOkwc+XJ8kf9JqQ5CqPhOZTZ5W5MbdxGs252jBn9elhWUlB+eULPSY=
  # SONATYPE_PASSWORD
  - secure: gboUzFKp2uq9b6i3W0nAQhpmbgmduF9lheD73j3+uGxDBX45CFbKS0ZZzZOq5x+YD7zKURGe+1LZ6RVx0OSqLIfkAtNbAeh5ef5iNRIIvMGHJIDZ9wN4aExrHV0R3IYF2rv1v8bHrLmt0RIeTk7e6jJ8woPYGomBwhb7VvoHzcgjyU8X3bHEird5TqEWNsRx8ZeN0cOuL2+L4P1Z27IjHZuSu8/EvniTkyrLTEFPIzFTCmWnNGxhePfovYxngGqmHQA8/soej/5+rFBleYbM5nhaLfH+EtYNd2UO518IkiZn9nOpFKS+pxj+HjlwHb4z805rFqivhY93PmIhNXpXFq1QY5j5nsMF7OwHFZt5+tgRhGg9FZnddPxOvbd00yM+6P4Xw1sLYbhNAzvqAsiElWqrfzumtGTM08g5TPHi8HSyqz4NS7nG/N+CqdZ5wsSy6d56cDZeM9infT0H3u6oA9GKg6I0e8sRFje4hUYav3orVdwkz3woiy2BkIcEp6119vPaUY2x9y/eTCnu7u0YU6nxiXCE3Zl0eM00acDajioDb5fjwk05FdiFTax39mCuXbSb/uuasTCQuSLnbrqOsFUl/+0klSHn/f57AQet0WJ2kj8Rygj+h0S8wXVvAAOsiVmUf81DlJw5DHMOm59wKf32U9Ik0sqTSiQJlVFiiEY=
  # DOCKER_USERNAME
  - secure: vpUA6xhESmKFQ/nhsrflT6L6s787OEbyGWrDzozoACwym1sXnDVAXv5K87Pn235ci1fBR3lfM1EbtZP/p5F02fqwJv+bf2b+zEYSnk4dcCl2d8Thr1fQQHsiE0u8dycZH/QZdAMfDP+rBBC+bvFgmw5XTGWCdSiDOC7efyw1CrIS5uQLRE7WZiG2ptgyHpkVo2KXu6E6NIpsqBg8DvbidrinqthRE5+Ab3BMj31+UD7zwRCQb6CRejGzi+O89A/UjCqrk24W25ZUcSBLNgCl6PNMf0aC/1qWmOSTWKAje9y0G/4SDzMSLGlYAs0V5Hkwzk2pM7lwSi5xmpvGYNP6l4LZprLgqdQGOMzuY7nGzfHZ2uN5gO2gEB5peYEl4lDQ6rhqhfmS0BSH7RXij5G+W5bUjybQ3zHrZM5gszzG8LZ4LBN7kOUimcqR+5i61hvisWYakDj2FLVZWMf+e+XYnL1xQbtYjR4kGdnv/PM0CvPzj5TG7LauNRcPphGE8QzDU53VUrG7LmZbz/fg5eW6b38CQLo4IJ/fYuBBOnDNnqVRxQSYyXWpvLpEy2bgrafA+qN67GAmCkMcwnBSCN0RDMchaFK3ZcC6Hrp5g1kUwgAhbwZoso06UH0tdzM+CfofvPoA3R40gwVlKmIo2wpNk0uLE0I+BAsVdikDHl4yRQ0=
  # DOCKER_PASSWORD
  - secure: pyqayEIpKwMX+D1Z61vuPbLk0X2EcD4qZY9HzyCSarXeglOoVR3o2AXeP5d+L7nLwjC5UJzE1MzvWsBl5a0sSVy5bWpRr5HxFE7VvlgDYWPcug1D6q1Dig9c37bPBqn3mZlrlaZfhJoA7wdIMitSUGLwZNmJ9sfKlWtc7FsZfiNHoofpeqB7dPJp7hM2I6FI7q0reB9+5cXmvivTrkU7FS3mSgTBhGKy9zm4tyc3OBP1mtdtUP/AmZ6CJYQMeuC8+q4kZl8SpJdFz16HIajoWdxEHuxDDClcGyqe0+cXZcfjq8s9bVxJxHgLAfx/MDfNfZ33jySEtXeUSuZ0DQYqE8CTJWwUPtulWKdfd5UoKQTWy1uQ431vD1EdMrdtgeDJIUgOU3wmsbqF8NQRp6h1qBTVIYUt/2snLN2/4Hf+LKhHe9R28JnjqpaW6dOedWkEXaYdXuHJiSno+/RRSngT/rmYRwbLJ+V+cjP++yvYUnN4rjFIZIu7dK0sp4V/7Z5nssMGcf4xLU2UAnQ7xTo/QFkh++hEGnJmS06V4SBAREBk2VNqZBDecGvvznG+zTSBPyMfv+V5k2+TLErXHHiY5FOw6FCryisNBADTdVWHM4AqwNp5K63lPsUvhdd1sY/mqL4P4Lq3XNQvXXJZIf4nWLGbqzN0+DZx/97TwIcofsw=
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- if [ "$CROSSDOCK" == true ]; then bash ./travis/install-crossdock-deps.sh ; fi
- sudo rm -rf /usr/local/bin/thrift
- sudo cp travis/docker-thrift/thrift /usr/local/bin/
script:
- if [ "$TESTS" == true ]; then make test ; else echo 'skipping tests'; fi
- if [ "$COVERAGE" == true ]; then ./gradlew codeCoverageReport ; else echo 'skipping
  coverage'; fi
- if [ "$CROSSDOCK" == true ]; then bash ./travis/build-crossdock.sh ; else echo 'skipping
  crossdock'; fi
after_success:
- if [ "$COVERAGE" == true ]; then bash <(curl -s https://codecov.io/bash) ; fi
- if [ "$CROSSDOCK" == true ]; then ./gradlew uploadArchives -PossrhUsername="${SONATYPE_USERNAME}"
  -PossrhPassword="${SONATYPE_PASSWORD}" ; fi
